// ═══ BASE QUESTIONS (사기업 + 공통) — 200문항 + IF 3문항 = 203문항 ═══
export const BASE_QUESTIONS = [
  // 개방성 (O) 23
  {id:1,dim:"O",text:"새로운 아이디어를 접하면 흥미가 생긴다.",rev:false},
  {id:2,dim:"O",text:"상상력이 풍부한 편이다.",rev:false},
  {id:3,dim:"O",text:"예술 작품을 감상하는 것을 즐긴다.",rev:false},
  {id:4,dim:"O",text:"기존 방식보다 새로운 방법을 시도하는 것을 선호한다.",rev:false},
  {id:5,dim:"O",text:"다양한 문화와 가치관에 관심이 많다.",rev:false},
  {id:6,dim:"O",text:"변화보다는 안정적인 환경이 편하다.",rev:true},
  {id:7,dim:"O",text:"복잡한 문제를 분석하는 것이 재미있다.",rev:false},
  {id:8,dim:"O",text:"철학적인 주제에 대해 깊이 생각해본 적이 있다.",rev:false},
  {id:9,dim:"O",text:"틀에 박힌 일상이 지루하게 느껴진다.",rev:false},
  {id:10,dim:"O",text:"새로운 취미를 시작하는 것에 적극적이다.",rev:false},
  {id:11,dim:"O",text:"익숙한 방식대로 하는 것이 가장 효율적이라고 생각한다.",rev:true},
  {id:12,dim:"O",text:"나만의 독특한 관점을 가지고 있다고 생각한다.",rev:false},
  {id:13,dim:"O",text:"모험적인 경험을 즐기는 편이다.",rev:false},
  {id:14,dim:"O",text:"추상적인 개념보다 구체적인 사실을 선호한다.",rev:true},
  {id:15,dim:"O",text:"낯선 환경에 놓이면 호기심이 먼저 든다.",rev:false},
  {id:16,dim:"O",text:"규칙을 따르는 것이 창의성보다 중요하다.",rev:true},
  {id:17,dim:"O",text:"새로운 음식이나 요리를 시도하는 것을 좋아한다.",rev:false},
  {id:18,dim:"O",text:"다큐멘터리나 교양 프로그램을 즐겨 본다.",rev:false},
  {id:19,dim:"O",text:"기발한 아이디어가 자주 떠오르는 편이다.",rev:false},
  {id:20,dim:"O",text:"검증된 방법만 사용해야 안심이 된다.",rev:true},
  {id:21,dim:"O",text:"여행지에서 현지인만 아는 장소를 찾아가는 편이다.",rev:false},
  {id:22,dim:"O",text:"정해진 매뉴얼대로 일하는 것이 편하다.",rev:true},
  {id:191,dim:"O",text:"토론에서 다양한 의견을 듣는 것이 즐겁다.",rev:false},
  // 성실성 (C) 24
  {id:23,dim:"C",text:"계획을 세우고 그대로 실행하는 편이다.",rev:false},
  {id:24,dim:"C",text:"맡은 일은 끝까지 책임지고 완수한다.",rev:false},
  {id:25,dim:"C",text:"약속 시간을 철저히 지킨다.",rev:false},
  {id:26,dim:"C",text:"정리정돈을 잘하는 편이다.",rev:false},
  {id:27,dim:"C",text:"목표를 정하면 꾸준히 노력한다.",rev:false},
  {id:28,dim:"C",text:"일을 미루는 경향이 있다.",rev:true},
  {id:29,dim:"C",text:"세부 사항까지 꼼꼼하게 확인한다.",rev:false},
  {id:30,dim:"C",text:"우선순위를 정해서 일을 처리한다.",rev:false},
  {id:31,dim:"C",text:"규칙과 절차를 잘 따른다.",rev:false},
  {id:32,dim:"C",text:"한 번 시작한 일은 중간에 포기하지 않는다.",rev:false},
  {id:33,dim:"C",text:"충동적으로 결정을 내릴 때가 많다.",rev:true},
  {id:34,dim:"C",text:"데드라인을 항상 지킨다.",rev:false},
  {id:35,dim:"C",text:"실수를 줄이기 위해 반복 확인한다.",rev:false},
  {id:36,dim:"C",text:"장기적인 목표를 가지고 있다.",rev:false},
  {id:37,dim:"C",text:"하루 일과를 체계적으로 관리한다.",rev:false},
  {id:38,dim:"C",text:"가끔 중요한 것을 깜빡할 때가 있다.",rev:true},
  {id:39,dim:"C",text:"작은 일이라도 최선을 다한다.",rev:false},
  {id:40,dim:"C",text:"주변 사람들이 나를 신뢰할 수 있다고 말한다.",rev:false},
  {id:41,dim:"C",text:"때로는 대충 넘어가는 것도 괜찮다고 생각한다.",rev:true},
  {id:42,dim:"C",text:"업무 일지나 기록을 꼼꼼히 남기는 편이다.",rev:false},
  {id:43,dim:"C",text:"결과물의 품질에 대한 기준이 높다.",rev:false},
  {id:44,dim:"C",text:"시간 관리를 잘하는 편이다.",rev:false},
  {id:192,dim:"C",text:"복잡한 프로젝트도 단계별로 나눠서 진행한다.",rev:false},
  {id:193,dim:"C",text:"어려운 과제도 끈기 있게 도전한다.",rev:false},
  // 외향성 (E) 23
  {id:45,dim:"E",text:"사람들과 어울리는 것이 에너지를 준다.",rev:false},
  {id:46,dim:"E",text:"모임에서 먼저 말을 거는 편이다.",rev:false},
  {id:47,dim:"E",text:"새로운 사람을 만나는 것이 즐겁다.",rev:false},
  {id:48,dim:"E",text:"조용한 환경에서 혼자 있는 것을 선호한다.",rev:true},
  {id:49,dim:"E",text:"회의에서 적극적으로 발언한다.",rev:false},
  {id:50,dim:"E",text:"파티나 행사에 참여하는 것을 좋아한다.",rev:false},
  {id:51,dim:"E",text:"대화할 때 주도적인 역할을 한다.",rev:false},
  {id:52,dim:"E",text:"혼자 보내는 시간이 길어지면 답답하다.",rev:false},
  {id:53,dim:"E",text:"여러 사람 앞에서 발표하는 것이 부담스럽지 않다.",rev:false},
  {id:54,dim:"E",text:"주말에는 집에서 쉬는 것이 가장 좋다.",rev:true},
  {id:55,dim:"E",text:"팀 활동을 개인 작업보다 선호한다.",rev:false},
  {id:56,dim:"E",text:"분위기를 띄우는 역할을 자주 한다.",rev:false},
  {id:57,dim:"E",text:"처음 보는 사람과도 쉽게 대화한다.",rev:false},
  {id:58,dim:"E",text:"사람이 많은 곳에 가면 피곤해진다.",rev:true},
  {id:59,dim:"E",text:"감정을 표현하는 데 거리낌이 없다.",rev:false},
  {id:60,dim:"E",text:"혼자 밥 먹는 것보다 같이 먹는 게 좋다.",rev:false},
  {id:61,dim:"E",text:"내 의견을 강하게 주장하는 편이다.",rev:false},
  {id:62,dim:"E",text:"조용히 관찰하는 편이다.",rev:true},
  {id:63,dim:"E",text:"전화 통화를 문자보다 선호한다.",rev:false},
  {id:64,dim:"E",text:"사교적이라는 말을 자주 듣는다.",rev:false},
  {id:65,dim:"E",text:"활기찬 환경에서 일할 때 집중이 잘 된다.",rev:false},
  {id:66,dim:"E",text:"네트워킹 자리에 적극적으로 참석한다.",rev:false},
  {id:194,dim:"E",text:"리더 역할을 맡는 것이 자연스럽다.",rev:false},
  // 친화성 (A) 24
  {id:67,dim:"A",text:"다른 사람의 감정에 공감을 잘한다.",rev:false},
  {id:68,dim:"A",text:"갈등 상황에서 중재 역할을 자주 한다.",rev:false},
  {id:69,dim:"A",text:"남을 돕는 것에서 보람을 느낀다.",rev:false},
  {id:70,dim:"A",text:"팀의 화합이 개인의 성과보다 중요하다.",rev:false},
  {id:71,dim:"A",text:"비판을 할 때 상대방의 기분을 고려한다.",rev:false},
  {id:72,dim:"A",text:"경쟁보다 협력을 선호한다.",rev:false},
  {id:73,dim:"A",text:"다른 사람의 실수에 관대한 편이다.",rev:false},
  {id:74,dim:"A",text:"상대방의 입장에서 생각하려고 노력한다.",rev:false},
  {id:75,dim:"A",text:"내 이익보다 팀의 이익을 우선시한다.",rev:false},
  {id:76,dim:"A",text:"누군가 어려움에 처하면 먼저 나서서 돕는다.",rev:false},
  {id:77,dim:"A",text:"사람들의 의도를 의심하는 편이다.",rev:true},
  {id:78,dim:"A",text:"양보하는 것이 어렵지 않다.",rev:false},
  {id:79,dim:"A",text:"불필요한 논쟁을 피하려고 한다.",rev:false},
  {id:80,dim:"A",text:"배려심이 깊다는 말을 자주 듣는다.",rev:false},
  {id:81,dim:"A",text:"팀원의 의견을 끝까지 경청한다.",rev:false},
  {id:82,dim:"A",text:"나와 다른 의견도 존중한다.",rev:false},
  {id:83,dim:"A",text:"솔직함이 배려보다 중요하다고 생각한다.",rev:true},
  {id:84,dim:"A",text:"갈등 상황에서 먼저 사과하는 편이다.",rev:false},
  {id:85,dim:"A",text:"타인의 성공을 진심으로 축하한다.",rev:false},
  {id:86,dim:"A",text:"자기주장이 강해서 부딪히는 경우가 있다.",rev:true},
  {id:87,dim:"A",text:"봉사 활동에 관심이 있다.",rev:false},
  {id:88,dim:"A",text:"조화로운 분위기를 만드는 데 기여한다.",rev:false},
  {id:195,dim:"A",text:"다른 사람을 칭찬하는 것이 자연스럽다.",rev:false},
  {id:196,dim:"A",text:"사람들과 따뜻한 관계를 유지하려고 노력한다.",rev:false},
  // 정서안정성 (N) 23
  {id:89,dim:"N",text:"스트레스 상황에서도 침착함을 유지한다.",rev:false},
  {id:90,dim:"N",text:"걱정이 많은 편이다.",rev:true},
  {id:91,dim:"N",text:"감정 기복이 적은 편이다.",rev:false},
  {id:92,dim:"N",text:"실패해도 빠르게 회복한다.",rev:false},
  {id:93,dim:"N",text:"사소한 일에 예민하게 반응할 때가 있다.",rev:true},
  {id:94,dim:"N",text:"압박감 속에서도 일을 잘 수행한다.",rev:false},
  {id:95,dim:"N",text:"비판을 들으면 오래 신경 쓰인다.",rev:true},
  {id:96,dim:"N",text:"어려운 상황에서 긍정적으로 생각하려 한다.",rev:false},
  {id:97,dim:"N",text:"불확실한 상황이 불안하다.",rev:true},
  {id:98,dim:"N",text:"감정에 휘둘리지 않고 이성적으로 판단한다.",rev:false},
  {id:99,dim:"N",text:"자존감이 높은 편이다.",rev:false},
  {id:100,dim:"N",text:"작은 실수에도 자책하는 편이다.",rev:true},
  {id:101,dim:"N",text:"예상치 못한 변화에도 유연하게 대응한다.",rev:false},
  {id:102,dim:"N",text:"기분이 쉽게 변하는 편이다.",rev:true},
  {id:103,dim:"N",text:"위기 상황에서 냉정하게 대처한다.",rev:false},
  {id:104,dim:"N",text:"남들의 시선이 신경 쓰인다.",rev:true},
  {id:105,dim:"N",text:"실패를 성장의 기회로 본다.",rev:false},
  {id:106,dim:"N",text:"쉽게 좌절하지 않는다.",rev:false},
  {id:107,dim:"N",text:"미래에 대한 막연한 불안을 느끼곤 한다.",rev:true},
  {id:108,dim:"N",text:"다른 사람과 비교하며 위축될 때가 있다.",rev:true},
  {id:109,dim:"N",text:"마음이 편안한 상태가 오래 유지된다.",rev:false},
  {id:110,dim:"N",text:"중요한 결정 앞에서 지나치게 고민한다.",rev:true},
  {id:197,dim:"N",text:"어떤 상황에서도 자신감을 잃지 않으려 한다.",rev:false},
  // 리더십 (L) 18
  {id:111,dim:"L",text:"팀을 이끌 때 방향을 제시하는 편이다.",rev:false},
  {id:112,dim:"L",text:"결단력 있게 의사결정을 내린다.",rev:false},
  {id:113,dim:"L",text:"사람들에게 동기부여를 잘한다.",rev:false},
  {id:114,dim:"L",text:"위임보다 직접 하는 것이 편하다.",rev:true},
  {id:115,dim:"L",text:"비전을 세우고 팀원과 공유한다.",rev:false},
  {id:116,dim:"L",text:"갈등 상황에서 최종 결정을 내릴 수 있다.",rev:false},
  {id:117,dim:"L",text:"책임을 지는 것이 부담스럽지 않다.",rev:false},
  {id:118,dim:"L",text:"팀원의 장단점을 파악하고 역할을 배분한다.",rev:false},
  {id:119,dim:"L",text:"프로젝트의 전체 그림을 먼저 그린다.",rev:false},
  {id:120,dim:"L",text:"어려운 상황에서도 팀을 안정시키는 역할을 한다.",rev:false},
  {id:121,dim:"L",text:"다른 사람을 이끌기보다 따르는 것이 편하다.",rev:true},
  {id:122,dim:"L",text:"회의에서 논의를 정리하고 결론을 도출한다.",rev:false},
  {id:123,dim:"L",text:"팀원들의 성장을 돕는 것이 보람 있다.",rev:false},
  {id:124,dim:"L",text:"의견이 갈릴 때 합의점을 찾아낸다.",rev:false},
  {id:125,dim:"L",text:"새로운 프로젝트를 시작할 때 먼저 나선다.",rev:false},
  {id:126,dim:"L",text:"리더보다는 실무자 역할이 더 잘 맞는다.",rev:true},
  {id:127,dim:"L",text:"조직의 목표와 개인의 목표를 연결시킨다.",rev:false},
  {id:128,dim:"L",text:"위기 상황에서 사람들이 나를 찾는 편이다.",rev:false},
  // 스트레스 대처 (S) 13
  {id:129,dim:"S",text:"마감이 촉박해도 업무 품질을 유지할 수 있다.",rev:false},
  {id:130,dim:"S",text:"동시에 여러 일을 처리하는 것이 가능하다.",rev:false},
  {id:131,dim:"S",text:"예상치 못한 문제가 생기면 대안을 빠르게 찾는다.",rev:false},
  {id:132,dim:"S",text:"업무 과부하 상황에서도 체계적으로 일한다.",rev:false},
  {id:133,dim:"S",text:"실패 후에도 동기부여를 스스로 할 수 있다.",rev:false},
  {id:134,dim:"S",text:"스트레스를 받으면 일의 효율이 크게 떨어진다.",rev:true},
  {id:135,dim:"S",text:"압박 속에서 오히려 집중력이 높아진다.",rev:false},
  {id:136,dim:"S",text:"여러 마감이 겹치면 패닉에 빠질 때가 있다.",rev:true},
  {id:137,dim:"S",text:"어려운 상황에서도 유머 감각을 유지한다.",rev:false},
  {id:138,dim:"S",text:"업무 외 시간에 스트레스를 효과적으로 해소한다.",rev:false},
  {id:139,dim:"S",text:"갑작스러운 업무 변경에도 빠르게 적응한다.",rev:false},
  {id:140,dim:"S",text:"장기적인 고강도 업무에도 번아웃 없이 버틸 수 있다.",rev:false},
  {id:200,dim:"S",text:"위기 상황을 오히려 성장 기회로 활용한다.",rev:false},
  // 자주성 (I) 19
  {id:141,dim:"I",text:"스스로 목표를 정하고 추진하는 편이다.",rev:false},
  {id:142,dim:"I",text:"지시를 받지 않아도 할 일을 찾아서 한다.",rev:false},
  {id:143,dim:"I",text:"자기 발전을 위해 스스로 학습한다.",rev:false},
  {id:144,dim:"I",text:"누군가 시켜야 움직이는 편이다.",rev:true},
  {id:145,dim:"I",text:"주도적으로 프로젝트를 제안한 경험이 있다.",rev:false},
  {id:146,dim:"I",text:"문제가 생기면 상사에게 먼저 보고하기보다 해결책을 찾는다.",rev:false},
  {id:147,dim:"I",text:"자기 일에 대한 주인의식이 강하다.",rev:false},
  {id:148,dim:"I",text:"명확한 지시가 없으면 불안하다.",rev:true},
  {id:149,dim:"I",text:"업무 개선 아이디어를 자발적으로 제안한다.",rev:false},
  {id:150,dim:"I",text:"혼자서도 일정 관리를 잘한다.",rev:false},
  {id:151,dim:"I",text:"상사의 피드백 없이도 자기 업무를 평가할 수 있다.",rev:false},
  {id:152,dim:"I",text:"수동적이라는 말을 듣는 편이다.",rev:true},
  {id:153,dim:"I",text:"새로운 업무에 자원해서 참여한다.",rev:false},
  {id:154,dim:"I",text:"자기계발에 시간과 비용을 투자한다.",rev:false},
  {id:155,dim:"I",text:"정해진 역할 외의 일도 필요하면 나서서 한다.",rev:false},
  {id:156,dim:"I",text:"다른 사람이 해주기를 기다리는 편이다.",rev:true},
  {id:157,dim:"I",text:"목표 달성을 위한 계획을 스스로 수립한다.",rev:false},
  {id:158,dim:"I",text:"자발적으로 행동한다는 말을 자주 듣는다.",rev:false},
  {id:198,dim:"I",text:"회사 일 외에도 자기만의 프로젝트를 진행한다.",rev:false},
  // 집중력 (F) 19
  {id:159,dim:"F",text:"한 가지 일에 깊이 몰입하는 편이다.",rev:false},
  {id:160,dim:"F",text:"주변이 시끄러워도 집중을 유지할 수 있다.",rev:false},
  {id:161,dim:"F",text:"업무 중 딴 생각을 잘 하지 않는다.",rev:false},
  {id:162,dim:"F",text:"장시간 같은 업무를 해도 집중력이 유지된다.",rev:false},
  {id:163,dim:"F",text:"쉽게 산만해지는 편이다.",rev:true},
  {id:164,dim:"F",text:"세밀한 작업을 오래 할 수 있다.",rev:false},
  {id:165,dim:"F",text:"한 번 시작하면 끝날 때까지 멈추지 않는다.",rev:false},
  {id:166,dim:"F",text:"여러 일을 동시에 하면 집중이 흐트러진다.",rev:true},
  {id:167,dim:"F",text:"복잡한 문서를 꼼꼼히 읽는 것이 어렵지 않다.",rev:false},
  {id:168,dim:"F",text:"업무 도중 SNS나 핸드폰을 자주 확인한다.",rev:true},
  {id:169,dim:"F",text:"중요한 일을 할 때 시간 가는 줄 모른다.",rev:false},
  {id:170,dim:"F",text:"집중해야 할 때 외부 방해를 차단할 수 있다.",rev:false},
  {id:171,dim:"F",text:"반복적인 업무에도 꾸준한 집중력을 발휘한다.",rev:false},
  {id:172,dim:"F",text:"회의 중 집중력을 끝까지 유지하기 어렵다.",rev:true},
  {id:173,dim:"F",text:"수치나 데이터를 다룰 때 실수가 적다.",rev:false},
  {id:174,dim:"F",text:"한 과제를 끝내기 전에 다른 과제로 넘어가곤 한다.",rev:true},
  {id:175,dim:"F",text:"정독이 필요한 자료를 잘 소화한다.",rev:false},
  {id:176,dim:"F",text:"몰입 상태에 들어가면 외부 자극을 잘 인지하지 못한다.",rev:false},
  {id:199,dim:"F",text:"마감 직전에 가장 높은 집중력을 발휘한다.",rev:false},
  // 사회적 바람직성 (SD) 5
  {id:177,dim:"SD",text:"나는 한 번도 거짓말을 한 적이 없다.",rev:false},
  {id:178,dim:"SD",text:"다른 사람에게 불만을 가져본 적이 전혀 없다.",rev:false},
  {id:179,dim:"SD",text:"나는 항상 모든 사람에게 공정하게 행동한다.",rev:false},
  {id:180,dim:"SD",text:"화가 난 적이 단 한 번도 없다.",rev:false},
  {id:181,dim:"SD",text:"나는 어떤 상황에서도 완벽하게 자기 통제를 한다.",rev:false},
  // 일관성 검증 (CC) 9
  {id:182,dim:"CC",text:"꼼꼼한 성격이라는 말을 자주 듣는다.",rev:false,pair:29},
  {id:183,dim:"CC",text:"사람들 사이에 있으면 힘이 난다.",rev:false,pair:45},
  {id:184,dim:"CC",text:"다른 사람의 아픔에 같이 슬퍼진다.",rev:false,pair:67},
  {id:185,dim:"CC",text:"항상 같은 방식대로 하는 것이 답답하게 느껴진다.",rev:false,pair:9},
  {id:186,dim:"CC",text:"웬만한 일에는 동요하지 않는 편이다.",rev:false,pair:91},
  {id:187,dim:"CC",text:"시키지 않아도 알아서 일을 찾아 한다.",rev:false,pair:142},
  {id:188,dim:"CC",text:"한 가지에 오래 집중하는 것이 자연스럽다.",rev:false,pair:159},
  {id:189,dim:"CC",text:"팀을 이끄는 것이 자연스럽다.",rev:false,pair:111},
  {id:190,dim:"CC",text:"압박 속에서도 평소 실력을 발휘한다.",rev:false,pair:129},
  // ═══ 비빈도 (IF - Infrequency) 3문항 — 정상인이면 거의 안 고르는 극단적 진술 ═══
  {id:401,dim:"IF",text:"가끔 현실이 꿈인지 구분이 안 될 때가 있다.",rev:false},
  {id:402,dim:"IF",text:"내 주변의 모든 사람들이 나를 감시하고 있다고 느낀 적이 있다.",rev:false},
  {id:403,dim:"IF",text:"가끔 내가 다른 사람의 몸에 들어가 있는 것 같은 느낌이 든다.",rev:false},
];

// ═══ 공공기관 추가 문항 (40문항) ═══
export const PUBLIC_QUESTIONS = [
  {id:301,dim:"ET",text:"규정이 불합리하더라도 정해진 절차를 따르는 것이 옳다고 생각한다.",rev:false},
  {id:302,dim:"ET",text:"업무상 알게 된 정보를 사적으로 이용한 적이 있다.",rev:true},
  {id:303,dim:"ET",text:"작은 편법이라도 용납해서는 안 된다고 생각한다.",rev:false},
  {id:304,dim:"ET",text:"공과 사를 명확히 구분하는 편이다.",rev:false},
  {id:305,dim:"ET",text:"부당한 지시를 받으면 거절할 수 있다.",rev:false},
  {id:306,dim:"ET",text:"결과가 좋으면 과정에서의 편법은 괜찮다고 생각한다.",rev:true},
  {id:307,dim:"ET",text:"투명하게 일을 처리하는 것이 가장 중요하다.",rev:false},
  {id:308,dim:"ET",text:"조직의 비리를 발견하면 신고할 의지가 있다.",rev:false},
  {id:309,dim:"ET",text:"금전적 유혹에 흔들리지 않을 자신이 있다.",rev:false},
  {id:310,dim:"ET",text:"주변 사람들이 하니까 나도 따라 한 적이 있다.",rev:true},
  {id:311,dim:"ET",text:"공공의 이익이 개인의 이익보다 우선이다.",rev:false},
  {id:312,dim:"ET",text:"청렴한 조직문화를 만드는 데 기여하고 싶다.",rev:false},
  {id:313,dim:"ET",text:"접대나 선물을 받는 것에 거부감이 없다.",rev:true},
  {id:314,dim:"ET",text:"양심에 따라 행동하는 것이 조직 논리보다 중요하다.",rev:false},
  {id:315,dim:"ET",text:"규정을 어기더라도 상사의 지시를 따라야 한다.",rev:true},
  {id:316,dim:"AS",text:"규칙은 어기기 위해 존재한다고 생각할 때가 있다.",rev:false},
  {id:317,dim:"AS",text:"다른 사람이 손해를 봐도 나와 상관없다고 느낀다.",rev:false},
  {id:318,dim:"AS",text:"법적으로 문제가 없으면 도덕적으로도 괜찮다고 생각한다.",rev:false},
  {id:319,dim:"AS",text:"약속을 지키지 않아도 큰 문제가 안 된다고 생각한다.",rev:false},
  {id:320,dim:"AS",text:"남에게 피해를 주더라도 내 목표 달성이 우선이다.",rev:false},
  {id:321,dim:"DT",text:"대부분의 사람들은 속마음이 다르다고 생각한다.",rev:false},
  {id:322,dim:"DT",text:"누군가 친절하면 뭔가 의도가 있을 것이라고 느낀다.",rev:false},
  {id:323,dim:"DT",text:"사람들을 쉽게 믿지 못한다.",rev:false},
  {id:324,dim:"DT",text:"동료의 조언도 일단 의심하고 본다.",rev:false},
  {id:325,dim:"DT",text:"사람들은 기회가 되면 나를 이용할 것이라고 생각한다.",rev:false},
  {id:326,dim:"AG",text:"화가 나면 참기 어렵다.",rev:false},
  {id:327,dim:"AG",text:"부당한 일을 당하면 즉시 따진다.",rev:false},
  {id:328,dim:"AG",text:"논쟁에서 지면 기분이 매우 나쁘다.",rev:false},
  {id:329,dim:"AG",text:"다른 사람의 실수에 쉽게 짜증이 난다.",rev:false},
  {id:330,dim:"AG",text:"가끔 물건을 던지거나 부수고 싶은 충동을 느낀다.",rev:false},
  {id:331,dim:"SV",text:"작은 변화에도 크게 동요하는 편이다.",rev:false},
  {id:332,dim:"SV",text:"업무 스트레스로 잠을 못 잔 적이 자주 있다.",rev:false},
  {id:333,dim:"SV",text:"예상치 못한 상황이 오면 아무것도 할 수 없다고 느낀다.",rev:false},
  {id:334,dim:"SV",text:"스트레스를 받으면 몸에 증상이 나타난다.",rev:false},
  {id:335,dim:"SV",text:"힘든 일이 겹치면 모든 것을 포기하고 싶어진다.",rev:false},
  {id:336,dim:"PA",text:"사람들이 내 뒤에서 나를 험담한다고 느낀 적이 있다.",rev:false},
  {id:337,dim:"PA",text:"나만 불공정한 대우를 받는다고 느낄 때가 있다.",rev:false},
  {id:338,dim:"PA",text:"다른 사람의 성공이 나를 의도적으로 무시하려는 것 같다.",rev:false},
  {id:339,dim:"PA",text:"사람들이 나를 일부러 배제한다고 느낀다.",rev:false},
  {id:340,dim:"PA",text:"나에 대한 평가가 불공정하다고 자주 느낀다.",rev:false},
];

export const CC_PAIRS=[[182,29],[183,45],[184,67],[185,9],[186,91],[187,142],[188,159],[189,111],[190,129]];

export const DIM_LABELS={O:"개방성",C:"성실성",E:"외향성",A:"친화성",N:"정서안정성",L:"리더십",S:"스트레스 대처",I:"자주성",F:"집중력",ET:"윤리성"};
export const DIMS_ORDER=["O","C","E","A","N","L","S","I","F"];
export const PUBLIC_DIMS=["ET"];
export const NEGATIVE_DIMS=["AS","DT","AG","SV","PA"];
export const NEG_LABELS={AS:"반사회성",DT:"대인불신",AG:"공격성",SV:"스트레스취약성",PA:"편집증"};

// ═══ 비빈도(IF) 탐지 설정 ═══
export const IF_IDS = [401, 402, 403];
export const IF_THRESHOLD = 4; // 4 이상 선택 시 비정상 응답

export const PERSONALITY_TYPES = [
  {name:"전략적 혁신가",emoji:"🚀",condition:(s)=>s.O>=75&&s.L>=70&&s.C>=65,
    desc:"새로운 아이디어와 비전을 제시하며, 이를 체계적으로 실행까지 이끌어내는 유형입니다.",
    strengths:"비전 제시, 창의적 문제해결, 전략적 사고",weaknesses:"완벽주의 경향, 타인의 속도에 대한 인내 부족",
    tips:["인성검사에서 '새로운 시도'와 '계획성' 문항에 모두 높게 응답하는 경향이 있어요. 모든 항목에 '매우 그렇다'만 찍으면 과장 응답으로 잡혀요.","혁신 성향이 강하면 '규칙 준수' 문항에서 점수가 낮아질 수 있는데, 기업은 균형을 봐요.","리더십 문항에서 '나 혼자 다 한다'보다 '팀과 함께 이끈다' 방향이 유리해요."],
    warnings:["과대 자기평가 경향이 있다면 일관성 검증에서 모순이 드러날 수 있어요.","개방성이 너무 높고 성실성이 낮으면 '실행력 부족'으로 분류돼요.","역문항을 놓치면 일관성 점수가 급락해요. 문항을 끝까지 읽으세요."]},
  {name:"안정적 실행가",emoji:"⚙️",condition:(s)=>s.C>=80&&s.N>=75&&s.S>=70,
    desc:"맡은 일을 묵묵히 완수하는 신뢰할 수 있는 유형입니다.",
    strengths:"책임감, 꾸준함, 위기 대응력",weaknesses:"변화에 대한 저항, 새로운 시도 주저",
    tips:["성실성이 높아 인성검사에서 유리한 편이에요.","'변화' 관련 문항에서 너무 부정적으로 답하면 '경직된 사람'으로 보여요.","스트레스 내성이 높다는 건 큰 장점이에요."],
    warnings:["성실성 문항에 전부 최고점 + 바람직성 문항에도 최고점이면 과장 응답으로 판정돼요.","역문항에서 일관성이 깨지기 쉬워요.","너무 완벽한 답변 패턴은 오히려 의심을 사요."]},
  {name:"소통형 리더",emoji:"🤝",condition:(s)=>s.E>=75&&s.A>=70&&s.L>=65,
    desc:"사람들과의 관계 속에서 시너지를 만들어내는 유형입니다.",
    strengths:"소통 능력, 팀 빌딩, 갈등 중재",weaknesses:"결단력 부족, 감정적 판단 경향",
    tips:["SK, LG 같은 협업 문화 기업에 잘 맞아요.","'결단력' 문항에서 낮으면 '결정 못 하는 리더'로 보여요.","갈등 상황에서 '합리적 조율' 방향이 좋은 평가를 받아요."],
    warnings:["외향+친화가 극단적으로 높으면 '자기 주관 없는 사람'으로 해석돼요.","감정 기복 문항에서 불안정하면 '감정적 사람'으로 분류돼요.","바람직성 문항에 높게 답하면 과장 응답에 걸려요."]},
  {name:"분석적 전문가",emoji:"🔬",condition:(s)=>s.O>=70&&s.C>=75&&s.F>=70,
    desc:"깊은 전문성과 집중력으로 문제의 본질을 파악하는 유형입니다.",
    strengths:"분석력, 전문성, 높은 집중력",weaknesses:"협업 시 소통 부족, 과도한 분석 경향",
    tips:["연구직, 기술직에 유리한 프로파일이에요.","외향성이 낮은 건 자연스러운 특성이에요.","팀 내 전문가 역할로서의 협업이 가능하다는 뉘앙스로 응답하세요."],
    warnings:["'사람을 피한다'가 아니라 '혼자 일할 때 효율적'으로 읽혀야 해요.","문항을 너무 깊이 분석하느라 시간이 오래 걸릴 수 있어요.","집중력이 높지만 협업 문항도 챙기세요."]},
  {name:"자율적 추진자",emoji:"🔥",condition:(s)=>s.I>=75&&s.L>=70&&s.S>=65,
    desc:"스스로 목표를 세우고 강한 자주성과 추진력으로 밀어붙이는 유형입니다.",
    strengths:"자주성, 추진력, 자기주도 학습",weaknesses:"독단적 판단, 협업 부족 가능",
    tips:["삼성, 현대차 같이 실행력을 강조하는 기업에서 높은 적합도를 보여요.","자주성이 높지만 친화성 문항도 챙겨야 '독불장군'으로 안 보여요.","'계산된 도전'의 뉘앙스가 중요해요."],
    warnings:["자주성 문항 전부 최고점 + 친화성 최저점이면 '협업 불가'로 분류돼요.","감정을 아예 안 느끼는 것처럼 답하면 비현실적으로 보여요.","'팀과 함께 해결한다'가 더 좋은 평가를 받아요."]},
  {name:"유연한 조율자",emoji:"🎯",condition:(s)=>s.A>=75&&s.N>=70&&s.S>=65,
    desc:"상황에 맞게 유연하게 대처하며, 팀의 균형을 잡아주는 유형입니다.",
    strengths:"유연성, 정서적 안정감, 팀워크",weaknesses:"주도성 부족, 자기주장 약함",
    tips:["대부분의 기업에서 안정적인 프로파일로 평가받아요.","리더십 문항에서 너무 소극적이면 '팔로워형'으로만 분류돼요.","자주성 문항에서도 적극적인 면을 보여주세요."],
    warnings:["모든 문항에 '보통'만 찍으면 '무성의한 응답'으로 판정돼요.","유연함과 우유부단함은 달라요.","자주성 점수가 너무 낮으면 불리해요."]},
  {name:"공감형 서포터",emoji:"💚",condition:(s)=>s.A>=80&&s.E>=60,
    desc:"따뜻한 공감 능력과 배려심으로 주변 사람들에게 신뢰를 받는 유형입니다.",
    strengths:"공감 능력, 신뢰 구축, 팀 문화 기여",weaknesses:"갈등 회피, 자기 의견 표현 부족",
    tips:["HR, CS, 교육 같은 사람 중심 직무에 적합해요.","논리적 판단력도 함께 봐요.","'경청 후 합리적 조율' 방향이 더 높은 평가를 받아요."],
    warnings:["친화성이 극단적으로 높으면 '자기 주관 없는 사람'으로 보여요.","바람직성 문항에 전부 동의하면 과장 응답으로 잡혀요.","자주성, 리더십 문항도 챙기세요."]},
  {name:"균형잡힌 올라운더",emoji:"⭐",condition:()=>true,
    desc:"전반적으로 균형 잡힌 성향을 보여주는 유형입니다.",
    strengths:"적응력, 범용성, 안정감",weaknesses:"뚜렷한 강점 부재, 차별화 어려움",
    tips:["균형잡힌 프로파일은 무난하지만 인상을 남기기 어려워요.","면접에서 차별화 포인트를 만들어야 해요.","최소 한두 개 차원에서는 강점을 보여주세요."],
    warnings:["모든 문항에 '보통'은 '무성의한 응답'으로 판정돼요.","뚜렷한 강점이 없으면 '굳이 뽑아야 할 이유'를 찾기 어려워요.","일관성 점수가 낮으면 '대충 풀었다'로 해석돼요."]},
];
